print('hello world')
print("please work")
print('hello world')
print("please work")


print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')
print('kkllshcskhukhukhu')


print('hello world')
print("please work")
print('hello world')
print("please work")
print('hello world')
print("please work")
print('hello world')
print("please work")
